DROP TABLE IF EXISTS mecz CASCADE;
DROP TABLE IF EXISTS bramka CASCADE;
DROP TABLE IF EXISTS klub CASCADE;
DROP TABLE IF EXISTS zawodnik CASCADE;
DROP TABLE IF EXISTS sedzia CASCADE;
DROP TABLE IF EXISTS stadion CASCADE;
DROP TABLE IF EXISTS termin CASCADE;

DROP VIEW IF EXISTS mecz_data;

DROP TRIGGER IF EXISTS sedzia_trigger ON sedzia;
DROP FUNCTION IF EXISTS sedzia_log_trigger;
DROP TABLE IF EXISTS sedzia_log;

DROP TRIGGER IF EXISTS ochrona_danych_triger ON klub;
DROP FUNCTION IF EXISTS ochrona_danych;